<a href="https://colab.research.google.com/github/JorgeBosquez/Tarea-03-Metodos-Numericos/blob/main/Descomposici%C3%B3n_LU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CONJUNTO DE EJERCICIOS

1.  Resuelva las siguientes multiplicaciones matriz-matriz:
    
    a. \[
    \begin{bmatrix}
    1 & 2 & 1 \\
    0 & 1 & 0 \\
    1 & 0 & 1
    \end{bmatrix}
    
    \begin{bmatrix}
    1 & 0 & 1 \\
    1 & 2 & 1 \\
    1 & 0 & 0
    \end{bmatrix}
    \]
    
    b. \[
    \begin{bmatrix}
    1 & 0 & 2 \\
    1 & 1 & 1 \\
    0 & 0 & 1
    \end{bmatrix}
    
    \begin{bmatrix}
    0 & 1 & 1 \\
    2 & 1 & 1 \\
    1 & 0 & 0
    \end{bmatrix}
    \]
    
    c. \[
    \begin{bmatrix}
    2 & 1 \\
    1 & 3 \\
    1 & 2
    \end{bmatrix}
    
    \begin{bmatrix}
    1 & 0 \\
    2 & 3
    \end{bmatrix}
    \]

In [1]:
import numpy as np

# 1a
A1a = np.array([[1, 2, 1], [0, 1, 0], [1, 0, 1]])
B1a = np.array([[1, 0, 1], [1, 2, 1], [1, 0, 0]])
result_1a = np.dot(A1a, B1a)

# 1b
A1b = np.array([[1, 0, 2], [1, 1, 1], [0, 0, 1]])
B1b = np.array([[0, 1, 1], [2, 1, 1], [1, 0, 0]])
result_1b = np.dot(A1b, B1b)

# 1c
A1c = np.array([[2, 1], [1, 3], [1, 2]])
B1c = np.array([[1, 0], [2, 3]])
result_1c = np.dot(A1c, B1c)

result_1a, result_1b, result_1c


(array([[4, 4, 3],
        [1, 2, 1],
        [2, 0, 1]]),
 array([[2, 1, 1],
        [3, 2, 2],
        [1, 0, 0]]),
 array([[4, 3],
        [7, 9],
        [5, 6]]))

2. Determine cuál de los siguientes matrices son de eigenvalores y cuál(es) no lo son mediante la matriz:
    
    a. \[
    \begin{bmatrix}
    1 & 2 \\
    2 & 3
    \end{bmatrix}
    \]
    
    b. \[
    \begin{bmatrix}
    4 & -2 \\
    1 & 1
    \end{bmatrix}
    \]
    
    c. \[
    \begin{bmatrix}
    2 & 1 \\
    1 & 2
    \end{bmatrix}
    \]

In [2]:
# 2a
A2a = np.array([[1, 2], [2, 3]])
eigenvalues_2a = np.linalg.eigvals(A2a)

# 2b
A2b = np.array([[4, -2], [1, 1]])
eigenvalues_2b = np.linalg.eigvals(A2b)

# 2c
A2c = np.array([[2, 1], [1, 2]])
eigenvalues_2c = np.linalg.eigvals(A2c)

eigenvalues_2a, eigenvalues_2b, eigenvalues_2c


(array([-0.23606798,  4.23606798]), array([3., 2.]), array([3., 1.]))

3. Resuelva los sistemas lineales que se tienen en la siguiente matriz de ecuaciones:

    \[
    \begin{cases}
    2x_1 + 3x_2 = 6 \\
    5x_1 + 7x_2 = 10
    \end{cases}
    \]
    
    \[
    \begin{cases}
    x_1 + x_2 = 2 \\
    3x_1 + 5x_2 = 4
    \end{cases}
    \]
    
    \[
    \begin{cases}
    2x_1 + 4x_2 = 6 \\
    2x_2 + 3x_1 = 1
    \end{cases}
    \]


In [3]:
# 3a
A3a = np.array([[2, 3], [5, 7]])
b3a = np.array([6, 10])
solution_3a = np.linalg.solve(A3a, b3a)

# 3b
A3b = np.array([[1, 1], [3, 5]])
b3b = np.array([2, 4])
solution_3b = np.linalg.solve(A3b, b3b)

# 3c
A3c = np.array([[2, 4], [2, 3]])
b3c = np.array([6, 1])
solution_3c = np.linalg.solve(A3c, b3c)

solution_3a, solution_3b, solution_3c


(array([-12.,  10.]), array([ 3., -1.]), array([-7.,  5.]))

### Ejercicio 4: Encontrar valores de \(\alpha\) que hacen que la matriz sea singular

Encuentre los valores de \(\alpha\) que hacen que la siguiente matriz sea singular:

\[
A = \begin{bmatrix}
1 & -1 & \alpha \\
2 & 2 & 1 \\
0 & \alpha & -\frac{3}{2}
\end{bmatrix}
\]


In [6]:
import sympy as sp

# Definir la variable simbólica
alpha = sp.symbols('alpha')

# Definir la matriz
A = sp.Matrix([
    [1, -1, alpha],
    [2, 2, 1],
    [0, alpha, -3/2]
])

# Calcular el determinante
det_A = A.det()

# Resolver la ecuación det(A) = 0
solutions_alpha = sp.solve(det_A, alpha)

det_A, solutions_alpha



(2*alpha**2 - alpha - 6.0, [-1.50000000000000, 2.00000000000000])

5. Resuelva los siguientes sistemas lineales:
    
    a. \[
    \begin{bmatrix}
    1 & 1 & 0 \\
    0 & 1 & 1 \\
    1 & 1 & 1
    \end{bmatrix}
    
    \begin{bmatrix}
    x \\
    y \\
    z
    \end{bmatrix}
    =
    \begin{bmatrix}
    1 \\
    2 \\
    3
    \end{bmatrix}
    \]
    
    b. \[
    \begin{bmatrix}
    3 & 2 & 0 \\
    1 & -1 & 0 \\
    0 & 5 & 1
    \end{bmatrix}
    
    \begin{bmatrix}
    x \\
    y \\
    z
    \end{bmatrix}
    =
    \begin{bmatrix}
    7 \\
    1 \\
    -2
    \end{bmatrix}
    \]
    
    c. \[
    \begin{bmatrix}
    1 & 2 & 1 \\
    2 & 3 & 4 \\
    3 & 1 & 5
    \end{bmatrix}
    
    \begin{bmatrix}
    x \\
    y \\
    z
    \end{bmatrix}
    =
    \begin{bmatrix}
    1 \\
    2 \\
    3
    \end{bmatrix}
    \]

In [7]:
# 5a
A5a = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1]])
b5a = np.array([1, 2, 3])
solution_5a = np.linalg.solve(A5a, b5a)

# 5b
A5b = np.array([[3, 2, 0], [1, -1, 0], [0, 5, 1]])
b5b = np.array([7, 1, -2])
solution_5b = np.linalg.solve(A5b, b5b)

# 5c
A5c = np.array([[1, 2, 1], [2, 3, 4], [3, 1, 5]])
b5c = np.array([1, 2, 3])
solution_5c = np.linalg.solve(A5c, b5c)

solution_5a, solution_5b, solution_5c


(array([1., 0., 2.]), array([ 1.8,  0.8, -6. ]), array([ 1.,  0., -0.]))

6. Para los siguientes ejercicios realice una descomposición \(LU\) mediante el algoritmo de Gaussiana sin \(LU\) con solo 1 permutación:
    
    a. \[
    \begin{bmatrix}
    2 & 3 & 1 \\
    4 & 7 & 3 \\
    6 & 2 & 5
    \end{bmatrix}
    \]

    b. \[
    \begin{bmatrix}
    4 & -2 & 1 \\
    20 & -7 & 12 \\
    -8 & 13 & 17
    \end{bmatrix}
    \]

In [8]:
import scipy.linalg

# 6a
A6a = np.array([[2, 3, 1], [4, 7, 3], [6, 2, 5]])
P6a, L6a, U6a = scipy.linalg.lu(A6a)

# 6b
A6b = np.array([[4, -2, 1], [20, -7, 12], [-8, 13, 17]])
P6b, L6b, U6b = scipy.linalg.lu(A6b)

(P6a, L6a, U6a), (P6b, L6b, U6b)


((array([[0., 0., 1.],
         [0., 1., 0.],
         [1., 0., 0.]]),
  array([[1.        , 0.        , 0.        ],
         [0.66666667, 1.        , 0.        ],
         [0.33333333, 0.41176471, 1.        ]]),
  array([[ 6.        ,  2.        ,  5.        ],
         [ 0.        ,  5.66666667, -0.33333333],
         [ 0.        ,  0.        , -0.52941176]])),
 (array([[0., 0., 1.],
         [1., 0., 0.],
         [0., 1., 0.]]),
  array([[ 1.        ,  0.        ,  0.        ],
         [-0.4       ,  1.        ,  0.        ],
         [ 0.2       , -0.05882353,  1.        ]]),
  array([[20.        , -7.        , 12.        ],
         [ 0.        , 10.2       , 21.8       ],
         [ 0.        ,  0.        , -0.11764706]])))

7. Modifique el algoritmo de eliminación gaussiana de forma que se pueda resolver una matriz en la forma general de descomposición \(LU\) sin permutación, resolviendo los sistemas siguientes lineales:
    
    \[
    \begin{bmatrix}
    1.002 & 0.999 & -3.001 \\
    3.001 & 3.000 & 0.001 \\
    2.000 & 1.999 & -1.000
    \end{bmatrix}
    \]
    
    a. \[
    \begin{bmatrix}
    1 \\
    2 \\
    3
    \end{bmatrix}
    \]
    
    b. \[
    \begin{bmatrix}
    0 \\
    1 \\
    1
    \end{bmatrix}
    \]
    
    c. \[
    \begin{bmatrix}
    1 \\
    1 \\
    1
    \end{bmatrix}
    \]

In [9]:
# 7
A7 = np.array([[1.002, 0.999, -3.001], [3.001, 3.000, 0.001], [2.000, 1.999, -1.000]])

b7a = np.array([1, 2, 3])
b7b = np.array([0, 1, 1])
b7c = np.array([1, 1, 1])

solution_7a = np.linalg.solve(A7, b7a)
solution_7b = np.linalg.solve(A7, b7b)
solution_7c = np.linalg.solve(A7, b7c)

solution_7a, solution_7b, solution_7c


(array([-2.80088133e+03,  2.80248249e+03, -2.60016150e+00]),
 array([-8.00480288e+02,  8.01080648e+02, -6.00360216e-01]),
 array([-200.32019212,  200.72043226,   -0.40024014]))